# These are supported funding model platforms

github: ayushmaanbhav
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: # Replace with your Tidelift package name
# community_bridge: # Replace with your community bridge project page
# liberapay: # Replace with your Liberapay username
# issuehunt: # Replace with your IssueHunt username
# otechie: # Replace with your Otechie username
# lfx_crowdfunding: # Replace with your LFX Crowdfunding project name
custom: ["upi://pay?pa=8544130924@pthdfc&pn=Ayush%20Jain&cu=INR"]
