package io.github.ayushmaanbhav.productFarm.entity.repository

import io.github.ayushmaanbhav.productFarm.entity.compositeId.AbstractAttributeRelatedAttributeId
import io.github.ayushmaanbhav.productFarm.entity.relationship.AbstractAttributeRelatedAttribute
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository

@Repository
interface AbstractAttributeRelatedAttributeRepo :
    JpaRepository<AbstractAttributeRelatedAttribute, AbstractAttributeRelatedAttributeId>
